version: '3.2'

services:
  todo:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=8080
      - PG_USER=admin
      - PG_PASSWORD=admin
      - PG_HOST=admin
      - PG_PORT=5432
      - PG_DB=todos
    ports:
      - 8080:8080
  postgres:
    image: postgres:11.5-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=todos
    ports:
      - 5433:5432
